### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by leo60228**
* Run Rustfmt
* Use Rust 2018 idioms (automatic, via `cargo fix`)
* Fix doctests (previously called the wrong methods; decryption on `XTSN` still doesn't work)
* Add example for how to decrypt an NCA header

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
👀

**Comment by leo60228** [comment]
@ThatNerdyPikachu if you want something right now, @roblabla already wrote a fully functional NCA parser and decryptor. Check the PRs in MegatonHammer/linkle. I'm not sure, but I think the reason it hasn't been merged might be because of romfs not being supported.

**Comment by roblabla** [comment]
It's not merged because I absolutely hate the code. It's over-generic in all the worst ways. I need to rewrite it using more composable interfaces (notably, I want to switch to using a ReadAt/WriteAt trait instead) but haven't found the time or motivation.

**Comment by roblabla** [comment]
(Also if you need a pure-rust XTS implementation, look at https://github.com/roblabla/block-ciphers/commit/b690b504e700b10ea42f9c9c6b5eca658ff2b578)

**Comment by ThatNerdyPikachu** [comment]
@leo60228 Thanks for the suggestion, but I already finished my NCA parser with that library (rob’s XTS) a month ago, lol.

**Comment by leo60228** [comment]
@ThatNerdyPikachu Is it public?

**Comment by ThatNerdyPikachu** [comment]
@leo60228 not atm.. I’ll put it up on a gist later tho — it do3s use OpenSSL, which id like to change.

**Pull request merged**
